backend:
  name: github
  repo: computer-lab/salon94design.com
  branch: master

media_folder: static/images
public_folder: public/static

collections:
  - name: designer
    label: Designer
    folder: src/data/designers
    create: true
    slug: "{{slug}}"
    format: yaml
    fields:
      - name: slug
        label: Slug
        widget: string
      - name: name
        label: Name
        widget: string
      - name: bio
        label: Bio
        widget: markdown
      - name: works
        label: Works
        widget: list
        fields:
          - name: title
            label: Title
            widget: string
          - name: slug
            label: Slug
            widget: string
          - name: when
            label: Year
            widget: number
          - name: projects
            label: Projects
            widget: list
            fields:
              - name: slug
                label: Project
                widget: relation
                collection: project
                searchFields: [slug, title]
                valueField: slug
          - name: tags
            label: Tags
            widget: list
          - name: images
            label: Images
            widget: list
            fields:
              - name: file
                label: File
                widget: image
          - name: caption
            label: Caption
            widget: string
          - name: price
            label: Price
            widget: string
          - name: medium
            label: Medium
            widget: string
          - name: dimensions
            label: Dimensions
            widget: string
  - name: project
    label: Project
    folder: src/data/projects
    create: true
    slug: "{{slug}}"
    format: yaml
    fields:
      - name: slug
        label: Slug
        widget: string
      - name: title
        label: Title
        widget: string
      - name: when
        label: Year
        widget: number
      - name: designers
        label: Designers
        widget: list
        fields:
          - name: slug
            label: Designer
            widget: relation
            collection: designer
            searchFields: [slug, name]
            valueField: slug
      - name: description
        label: Description
        widget: markdown
  - name: info
    label: Info
    folder: src/data/info
    create: false
    format: yaml
    fields:
      - name: email
        label: Email
        widget: string
      - name: instagram
        label: Instagram
        widget: string
      - name: phone
        label: Phone
        widget: string
      - name: mailingList
        label: Mailing List
        widget: string
      - name: aboutText
        label: About Us
        widget: markdown
      - name: press
        label: Press
        widget: list
        fields:
          - name: link
            label: Link
            widget: string
          - name: title
            label: Title
            widget: string
