backend:
  name: github
  repo: computer-lab/salon94design.com
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - name: designer
    label: Designer
    folder: src/data/designers
    create: true
    slug: "{{slug}}"
    format: yaml
    fields:
      - name: slug
        label: Slug (for url - unique, all lowercase, no spaces or special characters, no leading / trailing whitespace)
        widget: string
      - name: title
        label: Name
        widget: string
      - name: bio
        label: Bio
        widget: markdown
      - name: press
        label: Press
        widget: list
        default: []
        fields:
          - name: title
            label: Title
            widget: string
          - name: link
            label: Link
            widget: string
          - name: file
            label: PDF
            widget: file
      - name: works
        label: Works
        widget: list
        default: []
        fields:
          - name: title
            label: Title
            widget: string
          - name: slug
            label: Slug (for url - unique, all lowercase, no spaces or special characters, no leading / trailing whitespace)
            widget: string
          - name: when
            label: Year
            widget: number
          - name: projects
            label: Projects
            widget: list
            default: []
            fields:
              - name: slug
                label: Project
                widget: relation
                collection: project
                searchFields: [slug, title]
                valueField: slug
          - name: tags
            label: "Tags (ceramics, jewlery, lighting, other, seating, storage, tables, etc.) - any tag can be added, all lowercase"
            widget: list
            default: []
          - name: hero
            label: Hero
            widget: boolean
            default: false
          - name: images
            label: Images (filename all lowercase, no spaces or special characters)
            widget: list
            default: []
            fields:
              - name: file
                label: Cloudinary public id
                widget: string
          - name: video
            label: Video
            default: {vimeoId: '', caption: ''}
            widget: object
            fields:
              - name: vimeoId
                label: Vimeo ID
                widget: string
                default: ''
              - name: caption
                label: Caption
                widget: string
                default: ''
          - name: caption
            label: Caption
            widget: string
          - name: price
            label: Price
            widget: string
          - name: medium
            label: Medium
            widget: string
          - name: dimensions
            label: Dimensions
            widget: string
          - name: edition
            label: Edition
            widget: string
      - name: status
        label: Status
        widget: select
        options:
          - Available
          - Represented
        default: Available
  - name: project
    label: Project
    folder: src/data/projects
    create: true
    slug: "{{slug}}"
    format: yaml
    fields:
      - name: slug
        label: Slug (for url - unique, all lowercase, no spaces or special characters, no leading / trailing whitespace)
        widget: string
      - name: title
        label: Title
        widget: string
      - name: type
        label: Type
        widget: select
        options:
          - Exhibition
          - Art Fair
        default: Exhibition
      - name: when
        label: When
        widget: string
      - name: date
        label: Start Date (for sorting, use YYYY-MM-DD format)
        widget: text
      - name: designers
        label: Designers
        widget: list
        default: []
        fields:
          - name: slug
            label: Designer
            widget: relation
            collection: designer
            searchFields: [slug, name]
            valueField: slug
      - name: description
        label: Description
        widget: markdown
      - name: images
        label: Images (filename all lowercase, no spaces or special characters)
        widget: list
        default: []
        fields:
          - name: file
            label: Cloudinary public id
            widget: string
          - name: caption
            label: Caption
            widget: string
          - name: hero
            label: Hero
            widget: boolean
            default: false
      - name: video
        label: Video
        default: {vimeoId: '', caption: ''}
        widget: object
        fields:
          - name: vimeoId
            label: Vimeo ID
            widget: string
            default: ''
          - name: caption
            label: Caption
            widget: string
            default: ''
  - name: info
    label: Info
    folder: src/data/info
    create: false
    format: yaml
    fields:
      - name: hero
        label: Hero image - Cloudinary public id
        widget: string
      - name: staff
        label: Staff
        widget: list
        default: []
        fields:
          - name: name
            label: Name
            widget: string
          - name: title
            label: Title
            widget: string
          - name: email
            label: Email
            widget: string
      - name: emails
        label: Emails
        widget: list
        default: []
        fields:
          - name: title
            label: Title
            widget: string
          - name: email
            label: Email
            widget: string
      - name: social
        label: Social
        widget: list
        default: []
        fields:
          - name: title
            label: Title (ie, Instagram)
            widget: string
          - name: label
            label: Label / Handle (ie, @salon94design)
            widget: string
          - name: link
            label: Link (ie, https://www.instagram.com/salon94design)
            widget: string
      - name: phones
        label: Phones
        widget: list
        default: []
        fields:
          - name: title
            label: Title
            widget: string
          - name: number
            label: Phone Number
            widget: string
      - name: mailingList
        label: Mailing List
        widget: string
      - name: aboutText
        label: About Us
        widget: markdown
      - name: press
        label: Press
        widget: list
        default: []
        fields:
          - name: title
            label: Title
            widget: string
          - name: link
            label: Link
            widget: string
          - name: file
            label: PDF
            widget: file
      - name: images
        label: Images (filename all lowercase, no spaces or special characters)
        widget: list
        default: []
        fields:
          - name: title
            label: Title
            widget: string
          - name: file
            label: Cloudinary public id
            widget: string
  - name: landingPage
    label: Landing Page
    folder: src/data/landing-page
    create: false
    format: yaml
    fields:
      - name: featuredProjectSlug
        label: Featured Exhibition
        widget: relation
        collection: project
        searchFields: [slug, title]
        valueField: slug
      - name: featuredImage
        label: Featured exhibition image - Cloudinary public id
        widget: string
