backend:
  name: github
  repo: computer-lab/salon94design.com
  branch: master

media_folder: site/src/assets/images
public_folder: site/public/static

collections:
  - name: designer
    label: Designer
    folder: site/src/data/designers
    create: true
    slug: "{{slug}}"
    format: yaml
    fields:
      - name: slug
        label: Slug
        widget: string
      - name: name
        label: Name
        widget: string
      - name: bio
        label: Bio
        widget: markdown
      - name: works
        label: Works
        widget: list
        fields:
          - name: title
            label: Title
            widget: string
          - name: slug
            label: Slug
            widget: string
          - name: when
            label: Year
            widget: number
          - name: projects
            label: Projects
            widget: list
          - name: tags
            label: Tags
            widget: list
          - name: images
            label: Images
            widget: list
          - name: caption
            label: Caption
            widget: string
          - name: price
            label: Price
            widget: string
  - name: project
    label: Project
    folder: site/src/data/projects
    create: true
    slug: "{{slug}}"
    format: yaml
    fields:
      - name: slug
        label: Slug
        widget: string
      - name: title
        label: Title
        widget: string
      - name: bio
        label: Bio
        widget: text
      - name: when
        label: Year
        widget: number
      - name: designers
        label: Designers
        widget: list
      - name: description
        label: Description
        widget: text
  - name: info
    label: Info
    folder: site/src/data/info
    create: false
    format: yaml
    fields:
      - name: email
        label: Email
        widget: string
      - name: instagram
        label: Instagram
        widget: string
      - name: facebook
        label: Facebook
        widget: string
      - name: twitter
        label: Twitter
        widget: string
      - name: mailingList
        label: Mailing List
        widget: string
      - name: aboutText
        label: About Us
        widget: text
